<div id="content">
    <?php foreach ($this->products as $product) : ?>
        <div class="prod">
            <div class="prod-bgtop">
                <div class="prod-bgbtm">
                    <div class="oneitem">
                        <div class="image">
                            <?php echo $this->productImg($product->image, array('class' => 'imagefrm')) ?>
                        </div>
                        <div class="info">		      
                            <?php echo'<h1 class="title">Prodotto: ' . $product->name . '</h1>' ?>
                            <?php echo '<p class="meta">Descrizione Breve: ' . $product->descShort . '</p>' ?>
                        </div>
                        <div class="pricebox">
                            <?php echo $this->productPrice($product) ?>
                        </div>
                    </div>
                    <div class="entry">
                        <?php echo '<p>Descrizione Estesa: ' . $product->descLong . '</p>' ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>

    <!-- Paginazione -->	

    <?php
    if ($this->products instanceof Zend_Paginator) {
        echo $this->paginationControl($this->products, 'Sliding', 'public/_paginator.phtml');
    }
    ?>

</div>

<!-- fine sezione prodotti -->

<div id="sidebar">
    <ul>
        <li>
            <h2>Categorie</h2>
            <ul>
                <?php
                foreach ($this->topCategories as $category) {
                    echo '<li><a href=' . $this->url(array('controller' => 'public',
                        'action' => 'index',
                        'selTopCat' => $category->catId), 'default', true) .
                    '>' . $category->name . '</a><span>' . $category->desc . '</span></li>';
                }
                ?>
            </ul>
        </li>
<?php if (!is_null($this->selectedTopCat)) : ?>
            <li>
                <h2><?php echo 'In ' . $this->selectedTopCat ?></h2>
                <ul>
                    <?php
                    foreach ($this->subCategories as $subCategory) {
                        echo '<li><a href=' . $this->url(array('controller' => 'public',
                            'action' => 'index',
                            'selTopCat' => $subCategory->parId,
                            'selCat' => $subCategory->catId), 'default', true) .
                        '>' . $subCategory->name . '</a><span>' . $subCategory->desc . '</span></li>';
                    }
                    ?>
                </ul>
            </li>
<?php endif ?>
    </ul>
</div>
<!-- fine sezione laterale -->


