<ul>
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Catalogo</a></li>
	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'who'), 
                        'default',true
                    ); 
                 ?>"
		title="Il nostro profilo aziendale">Chi siamo</a></li>
	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'where'), 
                        'default',true
                    ); 
                 ?>"
		title="Dove trovarci">Dove Siamo</a></li>
	<li><a href="mailto:info@acme.it" title="Mandaci un messaggio">Contattaci</a></li>
	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                ), 
                        'default',true
                    ); 
                 ?>"
		title="Accesso utenti registrati">Login</a></li>
</ul>
