<?php
$this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
        ->appendFile($this->baseUrl('js/functions.js'))
        ->captureStart()
?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
var actionUrl='<?php echo $this->url(array('controller' => 'admin', 'action' => 'validateproduct',), 'default'); ?>';
var formName='<?php echo $this->productForm->getName() ?>';
$(":input").on('blur', function(event) {
var formElementId = $(this).attr('id');
doValidation(formElementId, actionUrl, formName);
});
});

<?php $this->headScript()->captureEnd() ?>

<div class="static">
    <h3>Aggiungi Prodotti</h3>
    <p>Utilizza questa form per inserire un nuovo prodotto nel Catalogo</p>
<?php echo $this->productForm ?>
</div>